name: Node.js CI

on: [push]

jobs:
  build_monorepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build apps
        run: npx nx run-many --all --target build --configuration production

      - uses: actions/upload-artifact@v2
        with:
          name: apps_dist
          path: dist/

  build:
    runs-on: ubuntu-latest
    needs: build_monorepo
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: apps_dist

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: ./apps/api
          tags: api:latest
          outputs: type=docker,dest=/tmp/api.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: /tmp/api.tar
