name: Node.js CI

on: [push]

jobs:
  build_monorepo:
    name: Build monorepo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build apps
        run: npx nx run-many --all --target build --configuration production

      - uses: actions/upload-artifact@v2
        with:
          name: apps_dist
          path: dist

  build_images:
    name: Build images
    runs-on: ubuntu-latest
    needs: build_monorepo
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: apps_dist

      - name: Check dirs
        run: ls

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build and export
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./apps/api
      #     tags: api:latest
      #     outputs: type=docker,dest=/tmp/api.tar

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: api
      #     path: /tmp/api.tar
